version: '3'

services:
    flask-app:
        container_name: flask-app
        build: ./app
        restart: always
        ports:
            - '5000:5000'
        volumes:
            - ./app:/app
        networks:
            - backend
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    mysql-db:
        container_name: mysql-db
        image: mysql:8.4.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: lixi
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - '33061:3306'
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        networks:
            - backend

networks:
    backend: