FROM python:3.11.9-alpine3.20

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . . 

CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0", "--port=5000"]