name: Build and Push to DockerHub
on:
  push:
      branches: ["master"]
jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python linter
        id: pylint
        uses: docker://reasonsoftware/action-pylint:v1
  sast:
    